### PR TITLE
Babylon compatibility fix

### PR DESCRIPTION
**Pull request by FreedomPrevails**

### CODE REVIEW

**Comment by utdrmac** [comment]
Attempted to test with this patch:

```
$ ./tezos-batch-payments.bash --skip-funding --debug --transactions tz1fHfqyAUzgyCbXs31uEjtsZ7TYaVrNr36i=1000000,tz1QYaYj9G9B2LoNj4DGrnBr1jNpb5R6VdT6=1000000
****************************************************************
***             Tezos Batch Payout Script                    ***
***                by Figment Networks                       ***
***              https://figment.network                     ***
*** https://github.com/figment-networks/tezos-batch-payments ***
****************************************************************

*** Warning: Not running in screen or tmux session!
*** Running anyway...

Checking node access... OK
Specify float account alias: bakingtacos
Using account 'bakingtacos'

Skipping funding (tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1 requires 2.003584 XTZ)...

Simulating... DEBUG -- Current head: "BM1Mx266EVyMvPr1ZVoFCi6akPDiPmt6geXW6tg56J18Ja5sQeT"
DEBUG -- Current counter: 73168
DEBUG -- Transactions with counter: [{"kind":"transaction","amount":"1000000","destination":"tz1fHfqyAUzgyCbXs31uEjtsZ7TYaVrNr36i","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73169"},{"kind":"transaction","amount":"1000000","destination":"tz1QYaYj9G9B2LoNj4DGrnBr1jNpb5R6VdT6","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73170"}]
DEBUG -- Simulation run JSON: {"operation":{"branch":"BM1Mx266EVyMvPr1ZVoFCi6akPDiPmt6geXW6tg56J18Ja5sQeT","contents":[{"kind":"transaction","amount":"1000000","destination":"tz1fHfqyAUzgyCbXs31uEjtsZ7TYaVrNr36i","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73169"},{"kind":"transaction","amount":"1000000","destination":"tz1QYaYj9G9B2LoNj4DGrnBr1jNpb5R6VdT6","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73170"}],"signature":"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"},"chain_id":"\"NetXdQprcVkpaWU\""}
Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/scripts/run_operation
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Unhandled error (Failure "Unexpected data (Chain_id)")
ERROR

Transaction simulation failed. Cannot continue!
INFO: {"operation":{"branch":"BM1Mx266EVyMvPr1ZVoFCi6akPDiPmt6geXW6tg56J18Ja5sQeT","contents":[{"kind":"transaction","amount":"1000000","destination":"tz1fHfqyAUzgyCbXs31uEjtsZ7TYaVrNr36i","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73169"},{"kind":"transaction","amount":"1000000","destination":"tz1QYaYj9G9B2LoNj4DGrnBr1jNpb5R6VdT6","storage_limit":"300","gas_limit":"15385","fee":"1792","source":"tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1","counter":"73170"}],"signature":"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"},"chain_id":"\"NetXdQprcVkpaWU\""}
```

**Comment by FreedomPrevails** [comment]
I fixed it in another commit.

**Comment by rfunduk** [comment]
Did they change the format of the response of the simulation? Wondering why you removed this line:

```
bash -c "echo '$run_response' | jq -e '.contents | map(select(.metadata.operation_result.status == \"failed\")) | length == 0' > /dev/null 2>&1"
```

I don't really like just checking it for the string `failed` instead of looking through the json.

Also is the storage update required, or? How did you arrive at these numbers? TezBox still has 1427 or whatever as the fee, for instance.

**Comment by rfunduk** [comment]
It looks like upping the gas limit fixes the errors. If you don't specify a high enough fee it just takes forever for the transaction to get confirmed. So I'll bump it up too but I don't think storage is needed.

I'll commit my earlier fix to the run_operation json structure and bump the fee/gas limit. Thanks for helping with this!

**Comment by FreedomPrevails** [comment]
The reason that I changed that line is that "run_operation" RPC is returning a much longer response now that in my case (sending like 200 transactions) was crashing the bash with error `Argument list too long`, Also my solution is more efficient and faster.
Regarding the storage limit, I got it from TRD. It was one of the changes in the commit so I thought may be there is a reason behind it.

**Comment by FreedomPrevails** [comment]
I still recommend you to merge my pull and change storage_limit to 0 if it is not necessary.
You master branch is crashing for me (high number of transactions).

**Comment by rfunduk** [comment]
Looks like it's because the json is too long an argument for `echo` basically. I'll see if I can figure out another way around it (like a tempfile or similar).

**Comment by FreedomPrevails** [comment]
Why would you do that when you can simply look for "failed" in the json string !?

**Comment by FreedomPrevails** [comment]
```
if [[ $run_response == *"failed"* ]]; then
  error "Transaction simulation failed. Cannot continue!" "$run_response"
else
  echo "OK"
fi
```

**Comment by rfunduk** [comment]
Because it relies on the substring `failed` only appearing for that single reason ;)

Took care of it just now, hopefully that works for you.

**Comment by FreedomPrevails** [comment]
Anyway thanks for your hard work :)

**Pull request closed without merging**
